should = require 'should'
Composite = require '../../lib/composite'
baseTest = require '../suite/lib/base'
nodeTest = require '../suite/lib/node'
eventedTest = require '../suite/lib/evented'
elementTest = require '../suite/lib/element'
shapeTest = require '../suite/lib/shape'
compositeTest = require '../suite/lib/composite'

baseTest Composite, 'Composite'
nodeTest Composite, 'Composite'
eventedTest Composite, 'Composite'
elementTest Composite, 'Composite'
shapeTest Composite, 'Composite'
compositeTest Composite, 'Composite'
