should = require 'should'
Primitive = require '../../lib/primitive'
baseTest = require '../suite/lib/base'
nodeTest = require '../suite/lib/node'
eventedTest = require '../suite/lib/evented'
elementTest = require '../suite/lib/element'
shapeTest = require '../suite/lib/shape'
compositeTest = require '../suite/lib/composite'

baseTest Primitive, 'Primitive'
nodeTest Primitive, 'Primitive'
eventedTest Primitive, 'Primitive'
elementTest Primitive, 'Primitive'
shapeTest Primitive, 'Primitive'
compositeTest Primitive, 'Primitive'
